[
  {
    change: '0.00',
    dca: 10.6783365,
    dcb: 10.6676635,
    currencyToken: {
      codigo: 'DOTUSDT',
      monedaOrigen: {
        description: 'Tether',
        simbolo: 'USDT',
        cripto: true,
        cantidadDecimales: 3,
        comercial: true,
        id: 7,
      },
      monedaDestino: {
        description: 'Polkadot',
        simbolo: 'DOT',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 28,
      },
      tipoTokenMoneda: {description: 'CRYPTO', id: 2},
      id: 45,
    },
  },
  {
    change: '0.00',
    dca: 68130.14805,
    dcb: 68062.05195000001,
    currencyToken: {
      codigo: 'RBTCUSDT',
      monedaOrigen: {
        description: 'Tether',
        simbolo: 'USDT',
        cripto: true,
        cantidadDecimales: 3,
        comercial: true,
        id: 7,
      },
      monedaDestino: {
        description: 'Rootstock Smart Bitcoin',
        simbolo: 'RBTC',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 30,
      },
      tipoTokenMoneda: {description: 'CRYPTO', id: 2},
      id: 51,
    },
  },
  {
    change: '-0.01',
    dca: 0.16764378,
    dcb: 0.16747621999999998,
    currencyToken: {
      codigo: 'DOGEUSDT',
      monedaOrigen: {
        description: 'Tether',
        simbolo: 'USDT',
        cripto: true,
        cantidadDecimales: 3,
        comercial: true,
        id: 7,
      },
      monedaDestino: {
        description: 'Dogecoin',
        simbolo: 'DOGE',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 24,
      },
      tipoTokenMoneda: {description: 'CRYPTO', id: 2},
      id: 38,
    },
  },
  {
    change: '-0.06',
    dca: 14.855424000000001,
    dcb: 14.840576,
    currencyToken: {
      codigo: 'UNIUSDT',
      monedaOrigen: {
        description: 'Tether',
        simbolo: 'USDT',
        cripto: true,
        cantidadDecimales: 3,
        comercial: true,
        id: 7,
      },
      monedaDestino: {
        description: 'Uniswap',
        simbolo: 'UNI',
        cripto: true,
        cantidadDecimales: 3,
        comercial: false,
        id: 14,
      },
      tipoTokenMoneda: {description: 'CRYPTO', id: 2},
      id: 25,
    },
  },
  {
    change: '-0.06',
    dca: 0.0000361090455,
    dcb: 0.0000360729545,
    currencyToken: {
      codigo: 'SHIBUSDT',
      monedaOrigen: {
        description: 'Tether',
        simbolo: 'USDT',
        cripto: true,
        cantidadDecimales: 3,
        comercial: true,
        id: 7,
      },
      monedaDestino: {
        description: 'SHIBA INU',
        simbolo: 'SHIB',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 23,
      },
      tipoTokenMoneda: {description: 'CRYPTO', id: 2},
      id: 37,
    },
  },
  {
    change: '0.00',
    dca: 1032.7691550000002,
    dcb: 987.7230000000001,
    currencyToken: {
      codigo: 'USDCUSD',
      monedaOrigen: {
        description: 'Dólares',
        simbolo: 'USD',
        cripto: false,
        cantidadDecimales: 2,
        comercial: false,
        id: 1,
      },
      monedaDestino: {
        description: 'USD Coin',
        simbolo: 'USDC',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 21,
      },
      tipoTokenMoneda: {description: 'FIAT', id: 1},
      id: 39,
    },
  },
  {
    change: '-0.00',
    dca: 1.052822925,
    dcb: 0.9976750574999999,
    currencyToken: {
      codigo: 'USDCARS',
      monedaOrigen: {
        description: 'Pesos',
        simbolo: 'ARS',
        cripto: false,
        cantidadDecimales: 2,
        comercial: true,
        id: 2,
      },
      monedaDestino: {
        description: 'USD Coin',
        simbolo: 'USDC',
        cripto: true,
        cantidadDecimales: 8,
        comercial: false,
        id: 21,
      },
      tipoTokenMoneda: {description: 'FIAT', id: 1},
      id: 40,
    },
  },
];
